apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: talos-ccm
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/roeldev/iac-talos-cluster.git
    targetRevision: HEAD
    path: manifests/talos-ccm
  destination:
    server: https://localhost:7445 # https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
