apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://github.com/Camphul/iac-talos-cluster
    targetRevision: HEAD
    path: manifests/cilium
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
