apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: talos-ccm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    path: manifests/talos-ccm
    repoURL: https://github.com/Camphul/iac-talos-cluster
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
