helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.12.2
    releaseName: metrics-server
    namespace: kube-system
    includeCRDs: true
    valuesFile: values.yaml
