global:
  clusterDomain: cluster.local

# Required configuration item
providerRegex: ""
# optional, specified as a string (enclosed with ""). if left empty, defaults to 367 days
maxExpirationSeconds: ""
# optional, permits to bypass dns resolution checks. default: false
bypassDnsResolution: false
# number of DNS SAN names allowed in a certificate request. defaults to 1
allowedDnsNames: 1
# optional, permits ignoring CSRs with another Username than `system:node:...`
ignoreNonSystemNode: false
