apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/roeldev/iac-talos-cluster
    targetRevision: HEAD
    path: manifests/argocd
  destination:
    server: https://localhost:7445 # https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
