apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: talos-ccm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    path: manifests/talos-ccm
    repoURL: https://github.com/roeldev/iac-talos-cluster.git
    targetRevision: HEAD
  destination:
    namespace: kube-system
    server: https://localhost:7445 # https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
