apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    path: apps/base
    repoURL: https://github.com/roeldev/iac-talos-cluster
    targetRevision: HEAD
  destination:
    namespace: default
    name: in-cluster
